"""代码生成器：把工程任务确定性地物化为真实代码文件。

增量"可用闭环"：这是兑现 "agents modify systems" 承诺的环节。
无需 LLM 凭证——用确定性模板把 frontend/backend 任务生成真实文件，
写入目标 repo 的 evocode_generated/ 子目录，并产出 ChangeSet（文件 + 内容）。
后续可把模板替换为真实 LLM 生成，接口不变。
"""
import os
import re


def _slug(text: str) -> str:
    """从意图/标题提取一个 PascalCase 标识符。"""
    words = re.findall(r"[A-Za-z0-9]+", text)
    if not words:
        return "Feature"
    # 取前 3 个词，PascalCase
    return "".join(w.capitalize() for w in words[:3]) or "Feature"


def _frontend_file(task: dict, intent: str) -> tuple[str, str]:
    name = _slug(task.get("title") or intent)
    path = f"evocode_generated/components/{name}.tsx"
    content = f"""// Generated by EvoCode for task {task.get('id')}: {task.get('title')}
// Intent: {intent}
import React from "react";

export interface {name}Props {{
  title?: string;
}}

export function {name}({{ title = "{name}" }}: {name}Props) {{
  return (
    <section className="evocode-{name.lower()}">
      <h2>{{title}}</h2>
      <p>{{/* TODO: implement: {task.get('description', '')} */}}</p>
    </section>
  );
}}

export default {name};
"""
    return path, content


def _backend_file(task: dict, intent: str) -> tuple[str, str]:
    name = _slug(task.get("title") or intent)
    path = f"evocode_generated/backend/{name}Controller.java"
    content = f"""// Generated by EvoCode for task {task.get('id')}: {task.get('title')}
// Intent: {intent}
package com.evocode.generated;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/{name.lower()}")
public class {name}Controller {{

    // TODO: implement: {task.get('description', '')}
    @GetMapping
    public String index() {{
        return "{name} endpoint generated by EvoCode";
    }}
}}
"""
    return path, content


def _test_file(task: dict, intent: str) -> tuple[str, str]:
    name = _slug(task.get("title") or intent)
    path = f"evocode_generated/tests/{name}.test.ts"
    content = f"""// Generated by EvoCode for task {task.get('id')}: {task.get('title')}
// Intent: {intent}
import {{ describe, it, expect }} from "vitest";

describe("{name}", () => {{
  it("is a placeholder test to be implemented", () => {{
    // TODO: {task.get('description', '')}
    expect(true).toBe(true);
  }});
}});
"""
    return path, content


def generate_files_for_task(task: dict, intent: str) -> list[dict]:
    """为单个任务生成文件。返回 [{path, content}]。"""
    kind = task.get("kind")
    if kind == "frontend":
        p, c = _frontend_file(task, intent)
    elif kind == "backend":
        p, c = _backend_file(task, intent)
    elif kind == "test":
        p, c = _test_file(task, intent)
    else:  # generic
        name = _slug(task.get("title") or intent)
        p = f"evocode_generated/{name}.md"
        c = f"# {task.get('title')}\n\nIntent: {intent}\n\nTODO: {task.get('description', '')}\n"
    return [{"path": p, "content": c}]


def generate_change_set(tasks: list[dict], intent: str) -> list[dict]:
    """为所有任务生成 ChangeSet：[{path, content}]。确定性。"""
    files: list[dict] = []
    for task in tasks:
        files.extend(generate_files_for_task(task, intent))
    return files


def apply_change_set(repo_path: str, files: list[dict]) -> list[str]:
    """把生成的文件写入目标 repo。返回已写入的绝对路径列表。
    仅写入 repo_path/evocode_generated/ 下，绝不覆盖 repo 既有文件。"""
    written: list[str] = []
    for f in files:
        rel = f["path"]
        # 安全：拒绝路径穿越，强制落在 evocode_generated/ 下
        if ".." in rel.split("/") or not rel.startswith("evocode_generated/"):
            continue
        abs_path = os.path.join(repo_path, rel)
        os.makedirs(os.path.dirname(abs_path), exist_ok=True)
        with open(abs_path, "w", encoding="utf-8") as fh:
            fh.write(f["content"])
        written.append(abs_path)
    return written
