"""代码生成器：把工程任务确定性地物化为真实代码文件。

增量"可用闭环"：这是兑现 "agents modify systems" 承诺的环节。
无需 LLM 凭证——用确定性模板把 frontend/backend 任务生成真实文件，
写入目标 repo 的 evocode_generated/ 子目录，并产出 ChangeSet（文件 + 内容）。
后续可把模板替换为真实 LLM 生成，接口不变。
"""
import os
import re


def _slug(text: str) -> str:
    """从意图/标题提取一个 PascalCase 标识符。"""
    words = re.findall(r"[A-Za-z0-9]+", text)
    if not words:
        return "Feature"
    # 取前 3 个词，PascalCase
    return "".join(w.capitalize() for w in words[:3]) or "Feature"


def _frontend_file(task: dict, intent: str) -> tuple[str, str]:
    name = _slug(task.get("title") or intent)
    path = f"evocode_generated/components/{name}.tsx"
    content = f"""// Generated by EvoCode for task {task.get('id')}: {task.get('title')}
// Intent: {intent}
import React from "react";

export interface {name}Props {{
  title?: string;
}}

export function {name}({{ title = "{name}" }}: {name}Props) {{
  return (
    <section className="evocode-{name.lower()}">
      <h2>{{title}}</h2>
      <p>{{/* TODO: implement: {task.get('description', '')} */}}</p>
    </section>
  );
}}

export default {name};
"""
    return path, content


def _backend_file(task: dict, intent: str) -> tuple[str, str]:
    name = _slug(task.get("title") or intent)
    path = f"evocode_generated/backend/{name}Controller.java"
    content = f"""// Generated by EvoCode for task {task.get('id')}: {task.get('title')}
// Intent: {intent}
package com.evocode.generated;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/{name.lower()}")
public class {name}Controller {{

    // TODO: implement: {task.get('description', '')}
    @GetMapping
    public String index() {{
        return "{name} endpoint generated by EvoCode";
    }}
}}
"""
    return path, content


def _test_file(task: dict, intent: str) -> tuple[str, str]:
    name = _slug(task.get("title") or intent)
    path = f"evocode_generated/tests/{name}.test.ts"
    content = f"""// Generated by EvoCode for task {task.get('id')}: {task.get('title')}
// Intent: {intent}
import {{ describe, it, expect }} from "vitest";

describe("{name}", () => {{
  it("is a placeholder test to be implemented", () => {{
    // TODO: {task.get('description', '')}
    expect(true).toBe(true);
  }});
}});
"""
    return path, content


def _patterns_comment(note: dict | None) -> str:
    """把架构笔记的模式/约束渲染为生成文件顶部的可追溯注释。"""
    if not note:
        return ""
    lines = []
    for p in note.get("patternsToFollow", []):
        lines.append(f"//   pattern: {p}")
    for c in note.get("constraints", []):
        lines.append(f"//   constraint: {c}")
    if note.get("impactWarning"):
        lines.append(f"//   impact: {note['impactWarning']}")
    if not lines:
        return ""
    return "// EvoCode architecture notes:\n" + "\n".join(lines) + "\n"


def generate_files_for_task(task: dict, intent: str, note: dict | None = None) -> list[dict]:
    """为单个任务生成文件。架构笔记存在时，优先使用其 fileLocations 与模式注释。

    内容优先用 LLM（gateway.generate_code）真实生成；provider 不支持或失败时回退
    到确定性模板，保证 generate 阶段绝不失败。文件落点（path）始终由模板/架构笔记决定。"""
    kind = task.get("kind")
    if kind == "frontend":
        p, c = _frontend_file(task, intent)
    elif kind == "backend":
        p, c = _backend_file(task, intent)
    elif kind == "test":
        p, c = _test_file(task, intent)
    else:  # generic
        name = _slug(task.get("title") or intent)
        p = f"evocode_generated/{name}.md"
        c = f"# {task.get('title')}\n\nIntent: {intent}\n\nTODO: {task.get('description', '')}\n"
    # 架构笔记接管文件落点（仅接受 evocode_generated/ 下的安全路径）
    primary = (note or {}).get("fileLocations", {}).get("primary")
    if primary:
        primary_norm = primary.replace("\\", "/")
        # 安全：规范化反斜杠后，要求落在 evocode_generated/ 下且无 .. 段（兼容 Windows 路径）
        if primary_norm.startswith("evocode_generated/") and ".." not in primary_norm.split("/"):
            p = primary_norm
    # 内容：优先 LLM 真实生成，失败回退上面的模板 c。
    llm_code = _try_llm_code(task, intent, note)
    if llm_code:
        return [{"path": p, "content": llm_code}]
    comment = _patterns_comment(note)
    if comment:
        c = comment + c
    return [{"path": p, "content": c}]


def _try_llm_code(task: dict, intent: str, note: dict | None) -> str | None:
    """尝试用 LLM 网关生成代码；任何情况（stub / 失败 / 导入问题）都安全返回 None。"""
    try:
        from evocode_runtime.llm import get_llm_gateway
        return get_llm_gateway().generate_code(task, intent, note)
    except Exception:  # noqa: BLE001  绝不让 codegen 因 LLM 而失败
        return None


def generate_change_set(tasks: list[dict], intent: str,
                        notes: list[dict] | None = None) -> list[dict]:
    """为所有任务生成 ChangeSet：[{path, content}]。确定性。

    notes（来自架构师阶段）按 taskId 匹配，决定文件落点与模式注释；缺省时退化为
    原有模板行为，保持向后兼容。"""
    by_task = {n.get("taskId"): n for n in (notes or [])}
    files: list[dict] = []
    for task in tasks:
        files.extend(generate_files_for_task(task, intent, by_task.get(task.get("id"))))
    return files


def apply_change_set(repo_path: str, files: list[dict]) -> list[str]:
    """把生成的文件写入目标 repo。返回已写入的绝对路径列表。
    仅写入 repo_path/evocode_generated/ 下，绝不覆盖 repo 既有文件。"""
    written: list[str] = []
    for f in files:
        rel = f["path"].replace("\\", "/")
        # 安全：规范化反斜杠后拒绝路径穿越，强制落在 evocode_generated/ 下（兼容 Windows）
        if ".." in rel.split("/") or not rel.startswith("evocode_generated/"):
            continue
        abs_path = os.path.join(repo_path, rel)
        os.makedirs(os.path.dirname(abs_path), exist_ok=True)
        with open(abs_path, "w", encoding="utf-8") as fh:
            fh.write(f["content"])
        written.append(abs_path)
    return written
